/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.project.hibernate.gui;


import com.project.hibernate.dao.MedecinDAO;
import com.project.hibernate.entity.Medecin;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tsila
 */
public class MedecinPanel extends javax.swing.JPanel implements MouseListener {

    /**
     * Creates new form MedecinPanel
     */
    private Medecin medecin = new Medecin();
    public MedecinPanel() {
        initComponents();
        setTable();
        selectMedecin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnAjoutMedecin = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableMedecin = new javax.swing.JTable();
        BtnModifierMedecin = new javax.swing.JToggleButton();
        BtnSupprimerMedein = new javax.swing.JToggleButton();

        setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        setMinimumSize(new java.awt.Dimension(2, 2));

        BtnAjoutMedecin.setForeground(new java.awt.Color(0, 0, 153));
        BtnAjoutMedecin.setText("Ajouter");
        BtnAjoutMedecin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAjoutMedecinActionPerformed(evt);
            }
        });

        TableMedecin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "codemed", "Nom", "Prénom", "Grade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TableMedecin);

        BtnModifierMedecin.setForeground(new java.awt.Color(0, 0, 153));
        BtnModifierMedecin.setText("Modifier");
        BtnModifierMedecin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModifierMedecinActionPerformed(evt);
            }
        });

        BtnSupprimerMedein.setForeground(new java.awt.Color(153, 0, 0));
        BtnSupprimerMedein.setText("Supprimer");
        BtnSupprimerMedein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSupprimerMedeinActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnAjoutMedecin)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnModifierMedecin)
                                .addGap(40, 40, 40)
                                .addComponent(BtnSupprimerMedein))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE))
                        .addGap(14, 14, 14))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(BtnAjoutMedecin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnModifierMedecin)
                    .addComponent(BtnSupprimerMedein))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAjoutMedecinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAjoutMedecinActionPerformed
        Medecin medecin = this.medecin;
        JDialogMedecin formAjoutMedecin = new JDialogMedecin(null,true,"New");
        formAjoutMedecin.setLocationRelativeTo(this);
        formAjoutMedecin.setVisible(true);
        selectMedecin();
// TODO add your handling code here:
    }//GEN-LAST:event_BtnAjoutMedecinActionPerformed

    private void BtnModifierMedecinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModifierMedecinActionPerformed
        
        if (medecin.getNom() == null) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionnée un médecin.", "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }
        JDialogMedecin formAjoutMedecin = new JDialogMedecin(null,true,"Update",this.medecin);
        System.out.println("Modifier Panel" +this.medecin.getCodemed());
        formAjoutMedecin.setVisible(true);
        selectMedecin();
    }//GEN-LAST:event_BtnModifierMedecinActionPerformed

    private void BtnSupprimerMedeinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSupprimerMedeinActionPerformed
 if (medecin.getNom() == null) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionnée un médecin.", "Erreur", JOptionPane.ERROR_MESSAGE);
                return;
            }
        JDialogMedecin formAjoutMedecin = new JDialogMedecin(null,true,this.medecin,"Delete");
        System.out.println("Supprimer Panel : "+this.medecin.getCodemed());
        formAjoutMedecin.setVisible(true);
        selectMedecin();
    }//GEN-LAST:event_BtnSupprimerMedeinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BtnAjoutMedecin;
    private javax.swing.JToggleButton BtnModifierMedecin;
    private javax.swing.JToggleButton BtnSupprimerMedein;
    private javax.swing.JTable TableMedecin;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
   DefaultTableModel tableModel = new DefaultTableModel(new Object[]{"codemed","Nom","Prenom","Grade"},0);
  private void setTable() {
    TableMedecin = new JTable(tableModel);
    TableMedecin.setCellSelectionEnabled(true);
    TableMedecin.addMouseListener(this);
    jScrollPane1.setViewportView(TableMedecin);
    //JScrollPane scrollPane = new JScrollPane(TableMedecin);
    //add(scrollPane); // Ajoute la table dans ton interface (assure-toi que c'est bien placé dans ton layout)
}

  private MedecinDAO medecinList = new MedecinDAO();
  private void selectMedecin() {
    tableModel.setRowCount(0); // Réinitialise le tableau
    
    medecinList.getAllMedecins().forEach(medecin -> {
        tableModel.addRow(new Object[]{
            medecin.getCodemed(),
            medecin.getNom(),
            medecin.getPrenom(),
            medecin.getGrade()
        });
    });
  }

    @Override
    public void mouseClicked(MouseEvent e) {
        if(e.getSource() == TableMedecin){
            if(e.getButton() == MouseEvent.BUTTON1){
                if(e.getClickCount() == 1){
                    int row =  TableMedecin.getSelectedRow();
                    if(row != -1){
                        int codemed = Integer.parseInt(TableMedecin.getValueAt(row, 0).toString());
                        String nom = TableMedecin.getValueAt(row, 1).toString();
                        String prenom = TableMedecin.getValueAt(row, 2).toString();
                        String grade = TableMedecin.getValueAt(row, 3).toString();
                        Medecin  medecin = new Medecin(codemed,nom,prenom,grade);
                        System.out.println();
                        this.medecin = medecin;
                    }
                }
            }
        }
   }

    @Override
    public void mousePressed(MouseEvent e) {
   }

    @Override
    public void mouseReleased(MouseEvent e) {
    }

    @Override
    public void mouseEntered(MouseEvent e) {
    }

    @Override
    public void mouseExited(MouseEvent e) {
   }
}


